### PR TITLE
Update GroupTripMap.java

### PR DESCRIPTION
**Pull request by ManojKumar121911**
This is for the Zoom issue , I have added code from line  62 to 65

### CODE REVIEW

**Comment by ksameersrk** [comment]
Bro, what is location variable bro?
where it is defined?
Did you build it?

**Comment by SarthakShetty** [comment]
He doesn't have android studio

**Comment by ManojKumar121911** [comment]
Now i corrected it , check dude

**Comment by ksameersrk** [comment]
Its not working. I will debug it later.

**Comment by ManojKumar121911** [comment]
k bro

**Pull request closed without merging**
